logging:
  file: ./tmp/checkmarx/logs/machina.log

cx-flow:
  bug-tracker: GITHUBPULL
  bug-tracker-impl:
     - Csv
     - CxXml
    # - GitHub
    # - GitLab
    # - Rally
    # - Json
  #enabled-vulnerability-scanners:
  # - sast
  # - sca
  #branches:
  #- master
  #- dev\w+
  #- release-\w+
  filter-severity:
   - High
   - Medium
  filter-category:
  #- SQL_Injection
  #- Stored_XSS
  #- Reflected_XSS_All_Clients
  filter-cwe:
  filter-status:
  # - Urgent
  # - Confirmed
  # - To Verify
  #mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  #wiki-url: https://custodela.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
  #codebash-url: https://checkmarx-demo.codebashing.com/courses/
  zip-exclude: tmp\/.*, target\/.*
  exclude-folders: tmp/
  exclude-files: "**/.git/**/*"

checkmarx:
  #version: 9.0
  #scope: access_control_api sast_rest_api
  username: ###<cxsast_username>###
  password: ###<cxsast_password>###
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: http://localhost
  #team: /CxServer
  url: ${checkmarx.base-url}/cxrestapi
  #scan-preset: Checkmarx Default
  #incremental: true
  #WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl
  preserve-xml: true
  report-timeout: 1800000 #miliseconds

#sca:
#  appUrl: https://sca.scacheckmarx.com
#  apiUrl: https://sca.scacheckmarx.com
#  accessControlUrl: https://platform.checkmarx.net
#  tenant:  ###<SCA Account Name>###
#  username: ###<SCA non-SSO username>###
#  password: ###<SCA password>###
#  filter-severity:
#  - High

#azure:
  #webhook-token: cxflow:12345
  #token: ###<ADOtoken>###
  #url: https://dev.azure.com/
  #issue-type: issue
  #api-version: 5.0
  #false-positive-label: false-positive
  #block-merge: true
  #closed-status: Done
  #open-status: "To Do"

#bitbucket:
  #webhook-token: 12345
  #token: ###<bitbucketuser>###:###<bitbuckettoken>###
  #url: https://api.bitbucket.org
  #api-path: /2.0

github:
  webhook-token: 12345
  token: ###<githubtoken>###
  url: https://github.com
  api-url: https://api.github.com/repos/
  false-positive-label: false-positive
  #block-merge: true
  #error-merge: true
  cx-summary: true
  flow-summary: false

#gitlab:
  #webhook-token: 12345
  #token: ###<gitlabtoken>###
  #url: https://gitlab.com
  #api-url: https://gitlab.com/api/v4/
  #false-positive-label: false-positive
  #block-merge: true

json:
  file-name-format: "[PROJECT].json"
  data-folder: "./tml/checkmarx/result"
  
cx-xml:
  file-name-format: "[PROJECT].json"
  data-folder: "./tml/checkmarx/result"

jira:
  url: ###<jira url>###
  username: ###<jira user email>###
  token: ###<jira api token>###
  project: APPSEC
  issue-type: Bug
  priorities:
    High: High
    Medium: Medium
    Low: Low
    Informational: Lowest
  open-transition: In Progress
  close-transition: Done
  open-status:
    - Backlog
    - Selected for Development
    - In Progress
  closed-status:
    - Done
  fields:
    - type: result
      name: application
      jira-field-name: Application
      jira-field-type: label
    - type: result
      name: cwe
      jira-field-name: CWEs
      jira-field-type: label
    - type: result
      name: category
      jira-field-name: Category
      jira-field-type: label
    - type: result
      name: loc
      jira-field-name: LOC
      jira-field-type: label
      jira-default-value: XXXXX